### ISSUE TITLE
Wording page d'accueil

### ISSUE THREAD

**Issue by martinregner** [incubateur-ademe/impactco2#84]
**Découvrez l’impact sur le climat
des objets ~~et gestes~~ de votre quotidien**

On en avait parlé, il n'y a pas vraiment de gestes à mon sens

**Comment by florianpanchout** [comment]
J'en rajoute petit à petit dans les synonymes. Essaie de taper "manger" par exemple :)

**Comment by martinregner** [comment]
Dac, en effet ;)
